### ISSUE TITLE
Feedback on Assignment

### ISSUE THREAD

**Issue by Gchism94** [asbollapragada/r-py-exercise-1#1]
Hi Anjani,

I've reviewed your latest commit. The R file has everything from the assignment, but I was expecting a .qmd file and a rendered HTML. If you need help doing this, please let me know. I chose these file types because they are more sharable and typically help with reproducibility. 

I'm okay with giving you full credit, but I will need to see the correct file types by September 15th. 
-Greg

**Comment by asbollapragada** [comment]
Good morning Greg,

Thank you for your email. I am working on the qmd file and will submit the
assignment by this weekend..

Best regards,
Anjani Somwya.

**Comment by Gchism94** [comment]
Great work! I am closing the issue. No further action is needed.
